#!/usr/bin/env python3
"""Generates src/assets/expressive.css: M3 Expressive motion springs and shapes.

Springs are the Material 3 Expressive motion scheme (stiffness, damping ratio)
sampled into CSS linear() easings with their settle time as duration. Shapes
are polar curves sampled with the same point count, so any two can morph into
each other with a clip-path transition or animation.

    python3 tools/gen_expressive.py
"""
import math
from pathlib import Path

SPRINGS = {  # name: (stiffness, damping ratio)
    "fast-spatial": (800, 0.6),
    "default-spatial": (380, 0.8),
    "slow-spatial": (200, 0.8),
    "fast-effects": (3800, 1.0),
    "default-effects": (1600, 1.0),
    "slow-effects": (800, 1.0),
}

POINTS = 60
SHAPES = {  # name: radius(theta), max radius normalised to fit the box
    "circle": lambda t: 1.0,
    "cookie4": lambda t: 1 + 0.10 * math.cos(4 * t),
    "cookie6": lambda t: 1 + 0.07 * math.cos(6 * t),
    "cookie9": lambda t: 1 + 0.06 * math.cos(9 * t),
    "cookie12": lambda t: 1 + 0.045 * math.cos(12 * t),
    "clover4": lambda t: 1 + 0.22 * abs(math.cos(2 * t)) ** 0.7,
    "burst": lambda t: 1 + 0.16 * math.cos(12 * t),
    "sunny": lambda t: 1 + 0.08 * math.cos(8 * t),
    "pentagon": lambda t: math.cos(math.pi / 5) / math.cos((t - math.pi / 2) % (2 * math.pi / 5) - math.pi / 5),
    "flower": lambda t: 1 + 0.18 * math.cos(6 * t) ** 3 + 0.04,
}


def spring(stiffness: float, zeta: float, n: int = 40) -> tuple[int, str]:
    w0 = math.sqrt(stiffness)

    def x(t: float) -> float:
        if zeta < 1:
            wd = w0 * math.sqrt(1 - zeta * zeta)
            return 1 - math.exp(-zeta * w0 * t) * (math.cos(wd * t) + zeta * w0 / wd * math.sin(wd * t))
        return 1 - math.exp(-w0 * t) * (1 + w0 * t)

    t, settle = 0.0, 3.0
    while t < 3:
        if all(abs(x(t + k * 0.004) - 1) < 0.002 for k in range(0, 60, 5)):
            settle = t
            break
        t += 0.002
    pts = ["0"] + [f"{x(settle * i / (n - 1)):.4f}" for i in range(1, n - 1)] + ["1"]
    return round(settle * 1000), ", ".join(pts)


def polygon(fn) -> str:
    rs = [fn(2 * math.pi * i / POINTS) for i in range(POINTS)]
    m = max(rs)
    pts = []
    for i, r in enumerate(rs):
        a = 2 * math.pi * i / POINTS - math.pi / 2
        pts.append(f"{50 + 50 * r / m * math.cos(a):.2f}% {50 + 50 * r / m * math.sin(a):.2f}%")
    return "polygon(" + ", ".join(pts) + ")"


out = ["/* Generated by tools/gen_expressive.py - do not edit by hand. */", "", ":root {"]
for name, (k, z) in SPRINGS.items():
    ms, pts = spring(k, z)
    out.append(f"  --m3-spring-{name}: linear({pts});")
    out.append(f"  --m3-spring-{name}-duration: {ms}ms;")
for name, fn in SHAPES.items():
    out.append(f"  --m3-shape-{name}: {polygon(fn)};")
out.append("}")
out.append("")
for name in SHAPES:
    out.append(f".shape-{name} {{\n  clip-path: var(--m3-shape-{name});\n}}")
out.append("")
# Expressive loading indicator: morphs through shapes while rotating.
seq = ["cookie9", "pentagon", "burst", "clover4", "sunny", "cookie4", "cookie9"]
frames = []
for i, name in enumerate(seq):
    frames.append(f"  {round(100 * i / (len(seq) - 1))}% {{\n    clip-path: var(--m3-shape-{name});\n  }}")
out.append("@keyframes m3-loading-morph {\n" + "\n".join(frames) + "\n}")
Path(__file__).resolve().parent.parent.joinpath("src/assets/expressive.css").write_text("\n".join(out) + "\n")
